project:
  type: website

website:
  title: "IS415 Journey"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "In-Class Exercises"
        menu:
        - text: "In-Class Exercise 2"
          href: inclass_ex/inclass_ex02/In-class_Ex02.qmd
        - text: "In-Class Exercise 3"
          href: inclass_ex/inclass_ex03/inclass_ex03.qmd
        - text: "In-Class Exercise 4"
          href: inclass_ex/inclass_ex04/inclass_ex04.qmd
        - text: "In-Class Exercise 5"
          href: inclass_ex/inclass_ex05/inclass_ex05.qmd
        - text: "In-Class Exercise 6"
          href: inclass_ex/inclass_ex06/inclass_ex06.qmd
        - text: "In-Class Exercise 7"
          href: inclass_ex/inclass_ex07/inclass_ex07.qmd
        - text: "In-Class Exercise 9"
          href: inclass_ex/inclass_ex09/inclass_ex09.qmd

          
      - text: "Hands-On Exercises"
        menu:
        - text: "Hands-On Exercise 2"
          href: handson_ex/handson_ex02/handson_ex02.qmd
        - text: "Hands-On Exercise 3"
          href: handson_ex/handson_ex03/handson_ex03.qmd
        - text: "Hands-On Exercise 4a"
          href: handson_ex/handson_ex04a/handson_ex04a.qmd
        - text: "Hands-On Exercise 4b"
          href: handson_ex/handson_ex04b/handson_ex04b.qmd
        - text: "Hands-On Exercise 7a"
          href: handson_ex/handson_ex07a/handson_ex07a.qmd
        - text: "Hands-On Exercise 7b"
          href: handson_ex/handson_ex07b/handson_ex07b.qmd
          
      - text: "Take-Home Exercises"
        menu:
        - text: "Take-Home Exercise 1"
          href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
        - text: "Take-Home Exercise 2"
          href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd
        - text: "Take-Home Exercise 3"
          href: Take-home_Ex/Take-home_Ex03/Take-home_Ex03.qmd
        
format:
  html:
    theme: [Zephyr, theme.scss]

editor: visual
